model:
  input_shape: [64, 256, 1]
  num_classes: 128
  character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?`~∫∑∏≠≤≥∈∉"

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  data_augmentation: true

paths:
  dataset: "ml/data/handwriting_dataset"
  preprocessed_dataset: "ml/data/handwriting_dataset/preprocessed"
  logs: "logs"
  best_model: "ml/models/best_model.h5"
  model_save: "ml/models/saved_model.h5"
  model_weights: "ml/models/model_weights.h5"
  model_versions: "ml/models/versions/"

huggingface:
  api_key: "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"
  models:
    handwritten_base: "microsoft/trocr-base-handwritten"
    handwritten_small: "microsoft/trocr-small-handwritten"
    math: "fhswf/TrOCR_Math_handwritten"

server:
  host: "0.0.0.0"
  port: 8000

logging:
  level: "INFO"
  directory: "logs"
  file: "app.log"
  max_size: 5242880  # 5 MB
  backup_count: 3

environment: "development"

gpu:
  use_gpu: true
  memory_growth: true

preprocessing:
  target_size: [128, 512]
  noise_reduction:
    method: "fastNlMeansDenoising"
    h: 10
    template_window_size: 7
    search_window_size: 21
  contrast_adjustment:
    method: "clahe"
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  binarization:
    method: "sauvola"
    window_size: 25
    k: 0.2
    R: 128
  skew_correction:
    method: "hough_transform"
    canny_threshold1: 50
    canny_threshold2: 150
    hough_threshold: 100

post_processing:
  spelling_correction:
    model: "bert-base-uncased"
  grammar_correction:
    enabled: true

firebase:
  credentials_path: "path/to/your/firebase-credentials.json"

dependencies:
  - firebase-admin
  - onnxruntime
  - tensorflow
  - torch
  - transformers
  - pywt
  - editdistance
  - numpy
  - pillow
  - opencv-python
  - scikit-learn
  - matplotlib

